"""
Motif export functions for various formats:
- XMS: NestedMICA XML format
- MEME: Minimal MEME format
- PFM: JASPAR Position Frequency Matrix

All functions take a list of CythonWeightMatrix objects.
"""

import numpy as np
from typing import List, Any, Optional


def export_xms(motifs: List[Any], filepath: str, log_evidence: float = 0.0, 
               version: str = "1.2.1") -> None:
    """
    Export motifs in XMS (NestedMICA XML) format.
    
    Args:
        motifs: List of CythonWeightMatrix objects.
        filepath: Output file path.
        log_evidence: Global log evidence value.
        version: Software version string.
    """
    with open(filepath, 'w') as f:
        f.write("<motifs>\n")
        f.write(f"<!-- Generated by NestedMICA Python v{version} -->\n")
        f.write(f"<!-- GlobalLogEvidence: {log_evidence:.4f} -->\n")
        
        for i, wm in enumerate(motifs):
            f.write(f"  <motif id='{i}' weight='1.0'>\n")
            f.write(f"    <weightMatrix length='{wm.get_length()}'>\n")
            columns = wm.get_columns()
            for pos in range(wm.get_length()):
                probs = np.power(2.0, columns[:, pos])
                probs = probs / probs.sum()
                f.write(f"      {probs[0]:.4f} {probs[1]:.4f} {probs[2]:.4f} {probs[3]:.4f}\n")
            f.write("    </weightMatrix>\n")
            f.write("  </motif>\n")
        f.write("</motifs>\n")


def export_meme(motifs: List[Any], filepath: str, 
                alphabet: str = "ACGT", strands: str = "+ -") -> None:
    """
    Export motifs in MEME Minimal format.
    
    Compatible with MEME Suite tools (FIMO, TOMTOM, etc.)
    
    Args:
        motifs: List of CythonWeightMatrix objects.
        filepath: Output file path.
        alphabet: DNA alphabet string.
        strands: Strand specification.
    """
    with open(filepath, 'w') as f:
        # MEME header
        f.write("MEME version 5\n\n")
        f.write(f"ALPHABET= {alphabet}\n\n")
        f.write(f"strands: {strands}\n\n")
        f.write("Background letter frequencies\n")
        f.write("A 0.25 C 0.25 G 0.25 T 0.25\n\n")
        
        for i, wm in enumerate(motifs):
            columns = wm.get_columns()
            length = wm.get_length()
            
            f.write(f"MOTIF MOTIF{i+1}\n")
            f.write(f"letter-probability matrix: alength= 4 w= {length}\n")
            
            for pos in range(length):
                probs = np.power(2.0, columns[:, pos])
                probs = probs / probs.sum()
                # MEME format: A C G T (space-separated)
                f.write(f" {probs[0]:.6f}  {probs[1]:.6f}  {probs[2]:.6f}  {probs[3]:.6f}\n")
            f.write("\n")


def export_pfm(motifs: List[Any], filepath: str, 
               motif_names: Optional[List[str]] = None) -> None:
    """
    Export motifs in JASPAR PFM (Position Frequency Matrix) format.
    
    Args:
        motifs: List of CythonWeightMatrix objects.
        filepath: Output file path.
        motif_names: Optional list of motif names.
    """
    with open(filepath, 'w') as f:
        for i, wm in enumerate(motifs):
            name = motif_names[i] if motif_names and i < len(motif_names) else f"MOTIF{i+1}"
            columns = wm.get_columns()
            length = wm.get_length()
            
            f.write(f">{name}\n")
            
            # PFM format: one row per base (A, C, G, T)
            for base_idx, base in enumerate(['A', 'C', 'G', 'T']):
                probs = []
                for pos in range(length):
                    p = np.power(2.0, columns[base_idx, pos])
                    probs.append(p)
                # Normalize row
                total = sum(probs)
                probs = [p / total * 100 for p in probs]  # Scale to ~counts
                f.write(f"{base} [ " + " ".join(f"{p:.1f}" for p in probs) + " ]\n")
            f.write("\n")


def export_transfac(motifs: List[Any], filepath: str,
                    motif_names: Optional[List[str]] = None) -> None:
    """
    Export motifs in TRANSFAC format.
    
    Args:
        motifs: List of CythonWeightMatrix objects.
        filepath: Output file path.
        motif_names: Optional list of motif names.
    """
    with open(filepath, 'w') as f:
        for i, wm in enumerate(motifs):
            name = motif_names[i] if motif_names and i < len(motif_names) else f"MOTIF{i+1}"
            columns = wm.get_columns()
            length = wm.get_length()
            
            f.write(f"AC  {name}\n")
            f.write(f"XX\n")
            f.write(f"ID  {name}\n")
            f.write(f"XX\n")
            f.write("P0      A      C      G      T\n")
            
            for pos in range(length):
                probs = np.power(2.0, columns[:, pos])
                probs = probs / probs.sum()
                counts = probs * 100  # Scale to pseudo-counts
                f.write(f"{pos+1:02d}  {counts[0]:5.1f}  {counts[1]:5.1f}  {counts[2]:5.1f}  {counts[3]:5.1f}\n")
            
            f.write("XX\n")
            f.write("//\n")
